### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Palomajol**
Statistics comparing the First Jet or Not workflow and T3 of the BOx the Jet workflow, filtered by SOL event

### CODE REVIEW

**Comment by ramanakumars** [comment]
This is really thorough analysis! I'm going to pause for a bit before merging and ask if you want to rewrite the core functions (calculating agreement, combining the data, masking agreement in T1 vs T3 vs combined, etc.) into a script, so that it can be called easily for other analyses? If this is not necessary, I can accept the merge.

**Comment by Palomajol** [comment]
I moved the SOL_class.py to aggregation, since that was how I build it in the first place as well. I only changed it last minute since I was not sure if it really classified as aggregation. Both SOL ipynb should be compatible with each other so files made by the first are useable in the second and the second now uses the correct import SOL_class from aggregation. I did not rewrite the SOL_analytics massively since the data read in takes so long I am not convinced it is useful to redo in other notebooks. Maybe if we find a use for those functions later.

**Comment by ramanakumars** [comment]
Could you remove lines 20-22 in the `SOL_class.py`:
```python
SOL_small,SOL_subjects,filenames0,times,Num,start,end,notes=np.loadtxt('SOL/SOL_{}_stats.csv'.format('Tc'),delimiter=',',unpack=True,dtype=str)
Num=Num.astype(float)
aggregator = Aggregator('reductions/point_reducer_hdbscan_box_the_jets.csv', 
                        'reductions/shape_reducer_hdbscan_box_the_jets.csv')
```

 I think we should be loading the data in the Jupyter notebook rather than directly in the module.

**Comment by Palomajol** [comment]
I kept those lines in there for better functionality, since a lot of functions need to use that data (SOL_small, obs_time etc). If I remove it in the class I would need to rewrite the functions to allow for the input of data. I kind of preferred the fact that no input was needed, but I can change it if needed. The aggregator load in seemed necessary since I cannot use the functions with the aggregator in the ipynb unless I read in the data in the SOL_class.py. I tried to do it with loading only in the ipynb but then the aggregator is not defined in the class and I cannot use those functions.

**Pull request merged**
